spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #cachePrepStmts=true
    #&useServerPrepStmts=true
    #&rewriteBatchedStatements=true
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: Abcds007
    hikari:
      auto-commit: false
      pool-name: mysql-pool-name
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 5
      minimum-idle: 5
  jpa:
    show-sql: true
#    Set batch size for and default value fetch from Dialect.DEFAULT_BATCH_SIZE
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        generate_statistics: true
        connection:
          autocommit: false

logging:
  level:
    root: info
    org:
      hibernate:
        engine:
          transaction:
            internal:
              org.hibernate.engine.transaction.internal.TransactionImpl: debug
      springframework:
        orm:
          jpa: debug
        transaction: debug