spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:  jdbc:mariadb://database-1.cxn7aglcvhjo.ap-southeast-3.rds.amazonaws.com:3306/spring_batching
    username: admin
    password: IkHZrjMVId57aaPc61ys

    hikari:
      auto-commit: false
      pool-name: mysql-pool-name
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 5
      minimum-idle: 5
  batch:
    job:
      enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 30
#        generate_statistics: true
        connection:
          autocommit: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    root: info
    org:
      hibernate:
        engine:
          transaction:
            internal:
              org.hibernate.engine.transaction.internal.TransactionImpl: debug
      springframework:
        orm:
          jpa: debug
        transaction: debug